baseURL = 'https://snprajwal.com'
title = 'Prajwal Nadig'
theme = 'hugo-coder'
publishDir = 'build'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'gruvbox'

[params]
author = 'Prajwal Nadig'
info = 'Renaissance man'
avatarurl = '/images/snprajwal.jpg'
since = 2022
colorScheme = 'dark'
# Open Graph params for link previews
description = 'Renaissance man'
images = ['/images/snprajwal.jpg']
# SEO keywords for home page
keywords = 'prajwal,snprajwal,prajwalsn,prajwal s n,prajwalnadig,prajwalnadig21,prajwal nadig'

[[params.social]]
icon = 'fa fa-envelope fa-2x'
name = 'Email'
url = 'mailto:prajwalnadig21@gmail.com'

[[params.social]]
icon = 'fa fa-linkedin fa-2x'
name = 'LinkedIn'
url = 'https://linkedin.com/in/snprajwal'

[[params.social]]
icon = 'fa fa-github fa-2x'
name = 'GitHub'
url = 'https://github.com/snprajwal'

[[menu.main]]
name = 'Résumé'
url = '/resume/'
weight = 1

[[menu.main]]
name = 'Folds'
url = '/folds/'
weight = 2

[[menu.main]]
name = 'Blog'
url = '/blog/'
weight = 3

[[menu.main]]
name = 'Tech'
url = '/tech/'
weight = 4

[[menu.main]]
name = 'About'
url = '/about/'
weight = 5
